defaults:
  - dataset: mnist
  - _self_

training:
  num_epochs: 10
  learning_rate: 0.001
  seed: 123
  model_dim: 16
  dropout_p: 0.2
  log_dir: ${hydra:runtime.cwd}/logs
  cache_dir: ${hydra:runtime.cwd}/cache 

npc:
  noise_rate: 0.2
  noise_mode: symmetric
  softplus_beta: 1.0
  n_neighbors: 10
  num_epochs: 10
  kld_reg: 1.0
  prior_norm: 5.0
  clipnorm: 1.0
